### ISSUE TITLE
2.4.0 doesn't build with QT 5.3.2 (Debian unstable)

### ISSUE THREAD

**Issue by marillat** [vkohaupt/vokoscreen#108]
Hi,
moc_screencast.cpp is badly generated. If you know why...

moc_screencast.cpp:302:16: error: expected unqualified-id before ‘int’
     QMetaType::Bool, QMetaType::QString,   15,
                          ^
moc_screencast.cpp:302:16: error: expected ‘}’ before ‘int’
moc_screencast.cpp:302:16: error: expected ‘,’ or ‘;’ before ‘int’
moc_screencast.cpp:342:1: error: expected declaration before ‘}’ token
 };

**Comment by vkohaupt** [comment]
Thanks for the hint. I see the that on my maschine, but i have no idea 
why this is. Maybe someone can look this error.

**Comment by AlfredoRamos** [comment]
It seems that is a Xlib.h issue as it also [defines Bool](http://www.opensource.apple.com/source/tcl/tcl-87/tk/tk/xlib/X11/Xlib.h).

Adding a ```#udef Bool``` before the class works. I've added this patch in the Arch git package.

[qvkscreenkey_fix.patch](https://aur4.archlinux.org/cgit/aur.git/plain/qvkscreenkey_fix.patch?h=vokoscreen-git)

Reference: https://forum.qt.io/topic/41817/expected-unqualified-id-before-int-with-qt5-3-only-for-bool-signal-and-slot/2

**Comment by marillat** [comment]
Alfredo,  thanks for the fix.

**Comment by vkohaupt** [comment]
Hey all,
looking over two houers where is the error, this error is not normal.
Look here and look there, and then i insert the X11 header files in cpp 
file and compile fine.
I do not understand it, but it is so.
Hm...

https://github.com/vkohaupt/vokoscreen/commit/41784d9d92bb2b95bd9c7dd6485423b1ba2ee43c

Thanks all for help
