### ISSUE TITLE
Current commit stage fails to build with g++ 4.9

### ISSUE THREAD

**Issue by eribertomota** [vkohaupt/vokoscreen#163]
Hi,

Trying to compile the vokoscreen git20161030.fb92c81 under g++-4.9 (Debian Jessie, stable), I got the following error:

screencast.cpp: In constructor ‘screencast::screencast()’:
screencast.cpp:68:58: error: ‘prettyProductName’ is not a member of ‘QSysInfo’
     qDebug() << "[vokoscreen]" << "Operating system:" << QSysInfo::prettyProductName();
                                                          ^
Makefile:1001: recipe for target 'screencast.o' failed

The 2.5 version builds fine.

Thanks!

Eriberto

**Comment by vkohaupt** [comment]
Hi,

You need min. Qt 5.4

http://doc.qt.io/qt-5/qsysinfo.html#prettyProductName

Volker

**Comment by eribertomota** [comment]
Thanks!
